version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   environment:
      GIT_EMAIL: 'github.afiqqo@gmail.com'
      GIT_NAME: 'afiqqo231'
      VERSION: '16.0'
      LINEAGE_MANIFEST: 'lineage-16.0'
      VENDOR: 'xiaomi'
      DEVICE: 'olive'
   steps:
      - run:
          command: |
           git config --global user.email "${GIT_EMAIL}"
           git config --global user.name "{GIT_NAME}"
           git config --global color.ui false
           repo init --depth=1 -u git://github.com/LineageOS/android.git -b ${LINEAGE_MANIFEST}
           repo sync
           git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${DEVICE}
           git clone https://github.com/afiqqo231/proprietary_vendor_xiaomi.git -b lineage-16.0 vendor/xiaomi
           git clone https://github.com/afiqqo231/kernel_olive_lolz.git -b V5 kernel/xiaomi/olive
           export USE_CCACHE=1
           export ALLOW_MISSING_DEPENDENCIES=true
           source build/envsetup.sh
           lunch lineage_olive-userdebug
           mka bacon
           export BUILDFILE=$(find $(pwd)/out/target/product/${DEVICE}/lineage*.zip 2>/dev/null)
           export UPLOAD_PATH=$(pwd)/out/target/product/${DEVICE}/upload/
           mkdir ${UPLOAD_PATH}
           cp $BUILDFILE $UPLOAD_PATH
           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Test Build for $(echo $DEVICE)" -b "LineageOS $(echo $VERSION)" -c ${CIRCLE_SHA1} -delete ${VERSION} ${UPLOAD_PATH}
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
